# Generated by Django 4.0.1 on 2022-02-19 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_employee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
    ]
