# Generated by Django 4.0.1 on 2022-02-19 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_employee_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='region',
            new_name='city',
        ),
    ]
